#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# When using Dockerfile, the venv is already present
pip install --upgrade uv
if [ ! -d "/home/vscode/.venvs/homeassistant" ]; then
    uv venv /home/vscode/.venvs/homeassistant --python /usr/local/bin/python
fi

source /home/vscode/.venvs/homeassistant/bin/activate
uv pip install --requirement requirements.txt --requirement dev-requirements.txt
python scripts/sync-modbus-pins.py
