name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DEFAULT_PYTHON: "3.14"

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"
    name: Pre-commit and pytest
    timeout-minutes: 30
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: pip

      - name: Install Python requirements
        run: |
          pip install -r requirements.txt -r dev-requirements.txt

      - name: Install core modbus requirements (from HA core manifest)
        run: python scripts/sync-modbus-pins.py

      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure --color=always

      - name: Debug Dependencies
        run: pip freeze

      - name: Run pytest
        run: |
          python -m pytest --timeout=10

  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    if: github.repository_owner == 'Xtherma-Warmepumpen'
    timeout-minutes: 10
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v7"

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"
          ignore: "topics"

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    timeout-minutes: 10
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v7"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
